version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: meiatwork/reverseproxy 
  backend_user:
    build:
      context: ../../udagram-api-user
    image: meiatwork/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed  
    image: meiatwork/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend  
    image: meiatwork/udagram-frontend
